### ISSUE TITLE
Component did mount again when context did changed

### ISSUE THREAD

**Issue by kuehnleon** [Spyna/react-context-hook#11]
I have a parent component which is using the `withAuth()` hook.
Inside of this Component I have an overall alert and besides this overall alert are some other child components. This child components also have some child components. 

My problem: I access the context via `useSetStoreValue` to set the context inside of the child component of the child to show my overall alert. The alert become visible correctly, but every time the context changed my component(functional component) did unmount and mount again. So in this case my component re-mount if the alert appears and also if it disappears after a few seconds.

Is there a way to prevent this kind of reload?

**Comment by Spyna** [comment]
This issue was due to the use of React Context API, which re-renders each time the "context" changes
From version 2.0.0 this issue is fixed because this library no longer uses React Context to storing the global state. And it now uses a subscription model, like react-redux. 

So you should update to version 2.0.0+

**Comment by kuehnleon** [comment]
Thanks for your fast reply. I tried your approach but the issue is still there. I upgraded to version 2.1.0
